web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainpage.urls')),
    path('', include('products.urls')),
    path('', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

# class Users(models.Model):
#     email = models.EmailField()
#     name = models.CharField(max_length=128)

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name=models.CharField(max_length=64, blank=True, null=True, default=None)
    category=models.ForeignKey(ProductCategory, blank=True, null=True, default=None, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    description=models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True, auto_now=False)
    updated=models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s, %s" % (self.price, self.name)

    class Meta:
        verbose_name='Товар'
        verbose_name_plural='Товары'


class ProductImage(models.Model):
    product=models.ForeignKey(Product, blank=True, null=True, default=None, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='products_images/')
    is_active=models.BooleanField(default=True)
    is_main=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True, auto_now=False)
    updated=models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.id

    class Meta:
        verbose_name='Фотография'
        verbose_name_plural='Фотографии'

templates/basket/basket.html
{% extends 'base.html' %}
{% block title %}Корзина ({{ products_total_count }}){% endblock %}
{% block content %}
{% load static %}
{% if products_in_basket %}
    <div class="container basket-list">
    {#     #}
              <table class="table text-center table-responsive">
                  <thead>
                      <tr>
                          <th>Фото</th>
                          <th>Название товара</th>
                          <th>Количество</th>
                          <th>Цена за единицу</th>
                          <th>Общая цена</th>
                          <th></th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for product_in_basket in products_in_basket %}
                           <tr>
                               <td>
                                   <img src="{{ product_in_basket.product.productimage_set.get.image.url }}" class="img-fluid basket-image">
                               </td>
                               <td>
                                   <p>{{ product_in_basket.product.name }}</p>
                               </td>
                               <td>
                                   <input value="{{ product_in_basket.count }}" type="number"
                                          step="1" min="1" max="100"
                                          class="product-in-basket-count">
                               </td>
                               <td>
                                   <span class="product-price">{{ product_in_basket.price_per_item }} KZT</span>
                               </td>
                               <td>
                                   <span class="total-product-in-basket-amount">{{ product_in_basket.total_price }} KZT</span>
                               </td>
                               <td>
                                   <button class="btn btn-success basket-btn delete-item"
                                       data-product_id="{{ product_in_basket.id }}"
                                       data-count="{{ product_in_basket.count }}">Удалить</button>
                               </td>
                           </tr>
                      {% endfor %}
                  </tbody>
              </table>

              <div class="text-center basket-total">
                  <p>Итого: <span id="total_order_amount">0</span> KZT</p>
              </div>
              <div class="text-center">
                  <a href="/checkout"><button type='submit' class="btn btn-primary checkout-btn">Заказать</button></a>
              </div>
    {#    </form>#}
    </div>
{% else %}
    <div class="container empty-basket">
        <div class="row">
            <div>
                <img class='icon' src="{% static 'media/icons/svg1.svg' %}" alt="dots icon">
                <p class="basket-total">Корзина пуста!</p>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}